export const metadata = {
  title: "Terms of Service — AccessOps AI",
  description: "Terms of Service for maitrico AccessOps AI.",
};

const EFFECTIVE = "2026-05-23";

export default function TermsPage() {
  return (
    <>
      <p className="text-xs uppercase tracking-wider text-ink-500 font-semibold">
        Effective {EFFECTIVE}
      </p>
      <h1>Terms of Service</h1>
      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of
        maitrico AccessOps AI (the &ldquo;Service&rdquo;), provided by maitrico
        (&ldquo;maitrico&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;). By creating an account or using the
        Service you agree to these Terms.
      </p>

      <h2>1. The Service</h2>
      <p>
        AccessOps AI is an accessibility assessment aid. It helps you identify
        and manage accessibility issues on websites you have permission to scan.
        It is <strong>not</strong> a legal certification tool. The Service does
        not guarantee compliance with the Americans with Disabilities Act (ADA),
        the European Accessibility Act (EAA), Web Content Accessibility
        Guidelines (WCAG), Section 508, EN 301 549, or any other law, regulation,
        or standard.
      </p>

      <h2>2. Eligibility and account responsibility</h2>
      <p>
        You must be at least 18 years old and able to form a binding contract.
        You are responsible for the activity that occurs under your workspace,
        including actions by your team members and anyone you invite. Keep your
        credentials confidential and notify us promptly at
        <a href="mailto:security@maitrico.com"> security@maitrico.com</a> if you
        suspect unauthorised access.
      </p>

      <h2>3. Permission to scan</h2>
      <p>
        You may only submit URLs you own, operate, or have explicit written
        permission to scan. Each scan requires you to affirm this permission.
        You agree not to use the Service to scan private dashboards, login-gated
        flows, or pages containing other people&apos;s sensitive personal data
        without a lawful basis. You must also respect the target site&apos;s
        <code> robots.txt</code> and rate-limit guidance.
      </p>

      <h2>4. Acceptable use</h2>
      <p>You will not:</p>
      <ul>
        <li>
          Use the Service to attack, probe, or stress-test systems you are not
          authorised to test.
        </li>
        <li>
          Attempt to bypass the synchronous and worker-side URL validation
          (which blocks private/loopback/cloud-metadata addresses).
        </li>
        <li>
          Resell, sublicense, or white-label the Service except as expressly
          permitted by your plan.
        </li>
        <li>
          Use the Service&apos;s AI features to generate content that
          misrepresents legal compliance status. AI output is filtered against a
          forbidden-claims list — circumvention is a breach of these Terms.
        </li>
      </ul>

      <h2>5. AI features</h2>
      <p>
        AI explanations and remediation suggestions are off by default per
        workspace and require explicit owner/admin consent in the Privacy &amp;
        Compliance Center. AI output is generated by third-party language
        models (currently Anthropic), can be incomplete or incorrect, and must
        be reviewed by a qualified person before being applied to your code or
        shared with clients.
      </p>

      <h2>6. Subscriptions, billing, and refunds</h2>
      <p>
        Paid plans are billed monthly via Stripe. Fees are charged in advance
        for the upcoming billing period. You can cancel at any time from the
        Customer Portal; cancellation takes effect at the end of the current
        period and we do not pro-rate refunds for partial periods.
      </p>
      <p>
        We may change pricing or plan limits with at least 30 days&apos; notice.
        Continued use after notice is acceptance of the new terms.
      </p>

      <h2>7. Your data, our data, AI training</h2>
      <p>
        You retain ownership of all content you submit (scan URLs, results,
        notes, reports). We do not sell your data and do not train models on
        customer content. We process your data only to operate the Service. See
        our <a href="/legal/privacy">Privacy Policy</a> and{" "}
        <a href="/legal/dpa">Data Processing Addendum</a> for details.
      </p>

      <h2>8. Disclaimer of warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo;. To the maximum extent permitted by
        law, maitrico disclaims all warranties, express or implied, including
        merchantability, fitness for a particular purpose, accessibility
        compliance, and non-infringement. Automated tools cannot detect every
        accessibility issue.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, maitrico&apos;s aggregate
        liability under these Terms will not exceed the amounts you paid us in
        the twelve (12) months preceding the event giving rise to the claim.
        Neither party will be liable for indirect, incidental, consequential,
        or punitive damages.
      </p>

      <h2>10. Indemnification</h2>
      <p>
        You will defend and indemnify maitrico against any third-party claim
        arising out of (a) your use of the Service in breach of these Terms,
        (b) URLs you submitted without permission, or (c) content you exported
        and distributed.
      </p>

      <h2>11. Termination</h2>
      <p>
        We may suspend or terminate your access if you materially breach these
        Terms, including by submitting URLs you are not authorised to scan or
        by abusing rate limits. You can terminate at any time by cancelling
        your subscription and deleting your workspace. Upon termination, scan
        data is retained per the workspace&apos;s configured retention window
        and then permanently deleted.
      </p>

      <h2>12. Governing law and disputes</h2>
      <p>
        These Terms are governed by the laws of the jurisdiction where
        maitrico is established (without regard to conflict-of-laws rules).
        Disputes will be resolved in the competent courts of that
        jurisdiction. If you are a consumer, mandatory consumer-protection
        rules of your country of residence still apply.
      </p>

      <h2>13. Changes</h2>
      <p>
        We may update these Terms from time to time. Material changes will be
        notified by email to workspace owners at least 30 days before they take
        effect. The &ldquo;Effective&rdquo; date at the top of this document reflects
        the latest version.
      </p>

      <h2>14. Contact</h2>
      <p>
        For questions about these Terms:{" "}
        <a href="mailto:legal@maitrico.com">legal@maitrico.com</a>. For privacy
        inquiries: <a href="mailto:privacy@maitrico.com">privacy@maitrico.com</a>.
      </p>
    </>
  );
}
