/**
 * Tests for POST /api/ai-assistant/brief.
 *
 * The gates we care about (input validation, workspace AI consent, rate
 * limiting) all run before the AI call, so mocking the session, the
 * limiter, the database and the generator is enough to exercise the
 * real handler — including the Markdown framing it adds around the
 * model's output.
 */
import { describe, it, expect, vi, beforeEach } from "vitest";

const {
  requireSessionMock,
  checkRateLimitMock,
  generateAssistantBriefMock,
  dbSelectMock,
  dbUpdateMock,
} = vi.hoisted(() => ({
  requireSessionMock: vi.fn(),
  checkRateLimitMock: vi.fn(),
  generateAssistantBriefMock: vi.fn(),
  dbSelectMock: vi.fn(),
  dbUpdateMock: vi.fn(),
}));

vi.mock("@/auth", () => ({
  auth: vi.fn(),
  handlers: {},
  signIn: vi.fn(),
  signOut: vi.fn(),
}));

vi.mock("@/lib/api/context", async () => {
  const actual = await vi.importActual<typeof import("@/lib/api/context")>(
    "@/lib/api/context"
  );
  return { ...actual, requireSession: requireSessionMock };
});

vi.mock("@/lib/api/rate-limit", () => ({ checkRateLimit: checkRateLimitMock }));
vi.mock("@/lib/api/audit", () => ({ audit: vi.fn() }));
vi.mock("@/lib/db", () => ({
  db: { select: dbSelectMock, update: dbUpdateMock },
}));

vi.mock("@/lib/ai/assistant", async () => {
  const actual = await vi.importActual<typeof import("@/lib/ai/assistant")>(
    "@/lib/ai/assistant"
  );
  return { ...actual, generateAssistantBrief: generateAssistantBriefMock };
});

import { POST } from "./route";
import { AiUnavailableError } from "@/lib/ai/explain";

const SCAN_ID = "11111111-2222-4333-8444-555555555555";
const VALID_SESSION = { userId: "user-1", workspaceId: "ws-1", role: "owner" };

function makeRequest(body: unknown) {
  return new Request("http://localhost/api/ai-assistant/brief", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
  }) as unknown as Parameters<typeof POST>[0];
}

const VALID_BODY = {
  scanId: SCAN_ID,
  preset: "plan",
  framework: "React / Next.js",
  prompt: "Focus on the checkout flow",
  consentChecked: true as const,
};

/**
 * The handler runs three reads in order: privacy settings, the scan,
 * then the issues. Each is a drizzle builder chain ending in an
 * awaitable, so we hand back a thenable that resolves to the next
 * queued result.
 */
function queueSelects(results: unknown[][]) {
  let call = 0;
  dbSelectMock.mockImplementation(() => {
    const rows = results[call++] ?? [];
    const chain: Record<string, unknown> = {};
    for (const method of ["from", "where", "leftJoin", "limit", "orderBy"]) {
      chain[method] = () => chain;
    }
    chain.then = (resolve: (value: unknown) => unknown) => resolve(rows);
    return chain;
  });
}

const AI_ON = [{ workspaceId: "ws-1", aiProcessingEnabled: true }];
const SCAN = [
  {
    id: SCAN_ID,
    workspaceId: "ws-1",
    baseUrl: "https://northwind-shop.example/",
    pagesScanned: 12,
    completedAt: new Date("2026-08-20T00:00:00Z"),
    createdAt: new Date("2026-08-20T00:00:00Z"),
  },
];
const ISSUES = [
  {
    ruleId: "button-name",
    severity: "critical",
    impact: "critical",
    description: "Buttons must have discernible text",
    help: "Buttons must have an accessible name",
    wcagTagsJson: ["wcag2a", "wcag412"],
    htmlSnippet: "<button></button>",
    pageUrl: "https://northwind-shop.example/cart",
  },
];

beforeEach(() => {
  requireSessionMock.mockReset();
  checkRateLimitMock.mockReset();
  generateAssistantBriefMock.mockReset();
  dbSelectMock.mockReset();
  dbUpdateMock.mockReset();

  requireSessionMock.mockResolvedValue(VALID_SESSION);
  checkRateLimitMock.mockResolvedValue({ ok: true, remaining: 19, reset: 0 });
  generateAssistantBriefMock.mockResolvedValue({
    markdown: "## Summary\n\nFix `button-name` first.",
    modelProvider: "anthropic",
  });
  dbUpdateMock.mockImplementation(() => {
    const chain: Record<string, unknown> = {};
    chain.set = () => chain;
    chain.where = () => Promise.resolve();
    return chain;
  });
  queueSelects([AI_ON, SCAN, ISSUES]);
});

describe("POST /api/ai-assistant/brief", () => {
  it("returns a framed markdown document with a filename", async () => {
    const res = await POST(makeRequest(VALID_BODY));
    expect(res.status).toBe(200);
    const body = await res.json();

    expect(body.markdown).toMatch(/^# Remediation plan & sprint program/);
    expect(body.markdown).toMatch(/northwind-shop\.example/);
    expect(body.markdown).toContain("Fix `button-name` first.");
    // The non-legal notice travels with the file, like the CSV's
    // trailing DISCLAIMER row.
    expect(body.markdown).toMatch(/not a legal certification/i);
    expect(body.markdown).toMatch(/generated by AI models/i);
    expect(body.filename).toMatch(
      /^accessops-plan-northwind-shop\.example-\d{4}-\d{2}-\d{2}\.md$/
    );
    expect(body.modelProvider).toBe("anthropic");
    expect(body.rulesAnalyzed).toBe(1);
  });

  it("passes the ranked findings and the user's question to the generator", async () => {
    await POST(makeRequest(VALID_BODY));
    const arg = generateAssistantBriefMock.mock.calls[0][0];
    expect(arg.preset).toBe("plan");
    expect(arg.framework).toBe("React / Next.js");
    expect(arg.userPrompt).toBe("Focus on the checkout flow");
    expect(arg.counts.critical).toBe(1);
    expect(arg.issues[0].ruleId).toBe("button-name");
    // URLs are reduced to a path before they reach the model.
    expect(arg.issues[0].pagePath).toBe("/cart");
  });

  it("rejects a request without the consent checkbox", async () => {
    const withoutConsent: Record<string, unknown> = { ...VALID_BODY };
    delete withoutConsent.consentChecked;
    const res = await POST(makeRequest(withoutConsent));
    expect(res.status).toBe(400);
    expect(generateAssistantBriefMock).not.toHaveBeenCalled();
  });

  it("rejects an unknown preset", async () => {
    const res = await POST(makeRequest({ ...VALID_BODY, preset: "hack-the-site" }));
    expect(res.status).toBe(400);
  });

  it("403s when workspace AI processing is disabled", async () => {
    queueSelects([[{ workspaceId: "ws-1", aiProcessingEnabled: false }]]);
    const res = await POST(makeRequest(VALID_BODY));
    expect(res.status).toBe(403);
    await expect(res.json()).resolves.toMatchObject({ error: "ai_disabled" });
    expect(generateAssistantBriefMock).not.toHaveBeenCalled();
  });

  it("403s when the workspace has no privacy settings row at all", async () => {
    queueSelects([[]]);
    const res = await POST(makeRequest(VALID_BODY));
    expect(res.status).toBe(403);
  });

  it("429s when the assistant rate limit is exhausted", async () => {
    checkRateLimitMock.mockResolvedValue({
      ok: false,
      remaining: 0,
      reset: Date.now() + 60_000,
    });
    const res = await POST(makeRequest(VALID_BODY));
    expect(res.status).toBe(429);
    expect(generateAssistantBriefMock).not.toHaveBeenCalled();
  });

  it("404s a scan outside the caller's workspace", async () => {
    queueSelects([AI_ON, []]);
    const res = await POST(makeRequest(VALID_BODY));
    expect(res.status).toBe(404);
    await expect(res.json()).resolves.toMatchObject({ error: "scan_not_found" });
  });

  it("503s rather than faking output when AI is not configured", async () => {
    generateAssistantBriefMock.mockRejectedValue(new AiUnavailableError());
    const res = await POST(makeRequest(VALID_BODY));
    expect(res.status).toBe(503);
    await expect(res.json()).resolves.toMatchObject({ error: "ai_unavailable" });
  });
});
