import { describe, expect, it } from "vitest";
import catalog from "./translations.tr.json";
import { translateMessage } from "./translate";

const messages = catalog as Record<string, string>;

/**
 * Live-audit regression net (2026-09-07): the language toggle flipped
 * `html[lang]` but several marketing strings stayed English because their
 * catalog keys were missing. Every string a visitor meets on `/`, `/pricing`
 * and `/sample-report` must have a real Turkish rendering — not an English
 * fallback.
 */
const MARKETING_KEYS = [
  // Hero (split across styled spans; the composition must read as one sentence)
  "Find accessibility issues before they become",
  "problems.",
  // Header / nav
  "How it works",
  "Product",
  "Pricing",
  "Compliance",
  "Sign in",
  "Start free scan",
  "Start",
  "Open dashboard",
  "Menu",
  // Hero stats + CTAs
  "Findings",
  "Start free",
  "Get started",
  // Footer
  "Sample report",
  "For agencies",
  // Sample report page
  "Download PDF",
  "fictional data, real report structure",
  // 404
  "Back home",
  "This page could not be found.",
];

// Compliance constants render on landing/pricing/onboarding/reports. They are
// member expressions (COMPLIANCE_COPY.X), not string literals, so the catalog
// generator never sees them — this list is the only net keeping them covered.
const COMPLIANCE_KEYS = [
  "Percevia AI helps identify and manage accessibility issues. It does not guarantee legal compliance.",
  "Percevia AI helps identify and manage accessibility issues. Automated tools cannot detect every accessibility issue, and this product does not guarantee ADA, EAA, WCAG, Section 508, or EN 301 549 compliance. Consult a qualified accessibility or legal professional for formal compliance claims.",
  "Automated accessibility scanning has limitations. Human review may be required to verify findings and identify issues that automated checks cannot detect.",
  "AI-generated suggestion. Review before implementation.",
  "Some explanations, summaries, and remediation suggestions in this product are generated by AI models. AI output can be incomplete or incorrect. Always review AI suggestions before applying them to your code or sharing with clients.",
  "Human review may be required for issues that automated checks cannot fully verify.",
  "This report is an accessibility assessment aid, not a legal certification. It reflects findings at the time of the scan and does not certify compliance with any law, regulation, or standard.",
  "I confirm I own this website or have permission to scan it and capture diagnostic accessibility evidence.",
  "Do not scan private dashboards or pages containing sensitive personal data. Use authenticated scanning carefully and only on properties you own or operate.",
  "Percevia AI helps you identify and manage accessibility issues. It does not provide legal certification or guarantee compliance with any specific law, regulation, or standard.",
  "I understand that automated accessibility scanning has limitations and that human review may be required.",
  "Percevia AI is not an accessibility overlay. We do not recommend overlay-only fixes as a substitute for real remediation.",
  "Deleting scan data is permanent. Reports built from this scan will lose their underlying findings.",
  "Screenshots are captured only for diagnostic accessibility evidence. Avoid scanning pages containing personal, confidential, financial, medical, or highly sensitive information unless you have authorization.",
  "Visual evidence is diagnostic only and may contain third-party copyrighted or personal data. Do not redistribute publicly.",
];

/** Strings inside stateful client components (PricingCta, PublicCheckForm,
 *  MobileNavMenu, onboarding + auth forms). These render through React's
 *  `t()` — a missing key here is an English fallback on an interactive
 *  surface. */
const INTERACTIVE_KEYS = [
  "Activating…",
  "Plan activated ✓",
  "Checking…",
  "No issues found in the first HTML response",
  "What this check did not cover",
  "That is not the same as an accessible site: the checks this preview could not run are listed below.",
  "Automated",
  "score",
  "initial",
  "HTML only",
  "critical",
  "serious",
  "Back",
  "Continue",
  "Finish sign-in",
  "Signing in...",
  "Sending...",
  "Accepting…",
  "Accept invitation",
  "Confirm your email",
  "Back to sign-in",
  "Percevia AI reports findings; it does not certify compliance.",
  "I am doing a one-off check for someone else.",
];

/** Correctly identical in both languages — presence is what matters. */
const IDENTITY_KEYS = ["Türkiye", "DPA"];

/** Static user-facing API messages. Converted components render `t(error)`
 *  over server payloads, so every message the API can return needs a key —
 *  otherwise TR users see English error states. Dynamic payloads (with IDs,
 *  counts, URLs) intentionally stay English source data. */
const API_KEYS = [
  "Billing is not configured.",
  "Cancel or change an active subscription in the billing portal.",
  "Continuous monitoring is not available on your plan.",
  "Daily free capacity reached. Please try again tomorrow.",
  "Daily free workspace capacity reached.",
  "Enable AI processing in Privacy & Compliance first.",
  "Enter a complete public URL, including https://.",
  "Manual URLs must stay on the same origin as the website URL.",
  "Manual scans require at least one URL.",
  "No subscription to manage yet.",
  "Not found.",
  "Only owners or admins can change workspace settings.",
  "PDF generation failed. Server-side Chromium is unavailable or could not render the report.",
  "Paid plans are purchased through checkout, not selected directly.",
  "Paid plans are unavailable because billing is not configured.",
  "Provide at least one field to update.",
  "Provide either fromScanId or targetUrl.",
  "Scan data is temporarily unavailable while a database index is being prepared. Please try again shortly.",
  "Sitemap URL must stay on the same origin as the website URL.",
  "That address cannot be scanned. Use a public http or https URL.",
  "That monitoring frequency is not available on your plan.",
  "That plan is not available for self-service checkout.",
  "The instant checker is temporarily unavailable. Please try again shortly.",
  "The request is too large.",
  "This scan was started with AI explanations turned off.",
  "User has no workspace yet",
  "Wait for the scan to finish before deleting it.",
  "We could not analyze that page's initial HTML. It may block automated requests or require JavaScript.",
  "Workspace data is temporarily unavailable because Firestore quota was exceeded.",
  "Your plan has no available team seats.",
];

/** Strings inside the converted /app + shared stateful components (batch
 *  A–D) plus the `{count}` interpolation templates. Same rule as above:
 *  a missing key is an English fallback on an interactive surface. */
const APP_KEYS = [
  "{count} scan per day",
  "{count} scans per day",
  "Up to {count} page per scan",
  "Up to {count} pages per scan",
  "AI fix card",
  "Automated checkers cannot detect every violation. Step through this guide to review keyboard, screen reader, and layout behaviors. Results are saved to this scan with your name, so teammates see them and the report can cite them.",
  "By starting this scan you confirm you have authorization from the site owner.",
  "Complete a scan before asking the assistant for project-specific fixes.",
  "Copy work-record badge",
  "Describe known barriers and remediation work in plain language. This record does not determine legal compliance.",
  "Desktop · Tablet · Mobile",
  "Draft, publish, and link a transparent accessibility work record.",
  "Generate plain-language explanations and code fixes for each finding. Requires workspace AI consent.",
  "I understand AI output may be incorrect and will be reviewed before use.",
  "Monitoring re-scans the site automatically and alerts you to new critical issues or score drops.",
  "Page count may be lower if the crawler finds fewer same-domain links. Time is a rough estimate, not a guarantee.",
  "Paste this accessible HTML badge in your website footer. It links users to your hosted accessibility work record and does not claim certification.",
  "Preparing scan…",
  "Recommended steps",
  "Recorded by",
  "Screenshots help identify where accessibility issues appear. They may contain visible page content, so enable this only for websites you are authorized to audit.",
  "Your role can read these results but not record them.",
  "a teammate",
  "interactive states",
  "monitors used.",
  "passes per viewport",
  "plan saved",
  "revision",
];

describe("Turkish catalog coverage for public marketing routes", () => {
  it("translates every flagged marketing string (no English fallback)", () => {
    for (const key of [...MARKETING_KEYS, ...COMPLIANCE_KEYS, ...INTERACTIVE_KEYS, ...APP_KEYS, ...API_KEYS]) {
      expect(messages[key], `missing TR key: ${key}`).toBeDefined();
      expect(messages[key].trim().length, `empty TR value: ${key}`).toBeGreaterThan(0);
      expect(translateMessage(key, "tr")).not.toBe(key);
    }
    for (const key of IDENTITY_KEYS) {
      expect(messages[key], `missing TR key: ${key}`).toBe(key);
    }
  });

  it("composes the hero headline as grammatical Turkish", () => {
    const headline = [
      "Find accessibility issues before they become",
      "user",
      "and",
      "compliance",
      "problems.",
    ]
      .map((part) => translateMessage(part, "tr"))
      .join(" ");
    expect(headline).toBe(
      "Erişilebilirlik sorunlarını kullanıcı ve uyumluluk sorunlarına dönüşmeden bulun."
    );
  });

  it("has no empty translations anywhere in the catalog", () => {
    const empty = Object.entries(messages)
      .filter(([, value]) => value.trim().length === 0)
      .map(([key]) => key);
    expect(empty).toEqual([]);
  });
});
