/**
 * Render a report from DB content.
 *
 * Three flavors:
 *   - HTML: produced inline; can be returned as text/html or used to
 *     drive PDF generation later.
 *   - PDF: generated by sending the HTML to the worker via a `pdfFromHtml`
 *     queue (deferred — for MVP we serve the HTML and let the browser
 *     print to PDF). Documented in README.
 *   - CSV: flat issues table, no headers in the body.
 *
 * The disclaimer is always the last block of the HTML and is also
 * embedded as a trailing CSV row so exports can't be stripped of the
 * non-legal notice.
 */
import { COMPLIANCE_COPY } from "@/lib/microcopy/compliance";

export interface ReportInputIssue {
  id: string;
  ruleId: string;
  severity: string;
  impact: string;
  description: string;
  help: string;
  helpUrl?: string | null;
  wcagTags: string[];
  pageUrl: string | null;
  pageTitle: string | null;
  htmlSnippet?: string | null;
}

export interface ReportInput {
  title: string;
  workspaceName: string;
  scanId: string;
  baseUrl: string;
  pagesScanned: number;
  scanDate: Date;
  issues: ReportInputIssue[];
  counts: { critical: number; moderate: number; minor: number; passed: number; review: number };
}

const DISCLAIMER = COMPLIANCE_COPY.REPORT_NOT_LEGAL;

export function renderHtml(input: ReportInput): string {
  const sevCount = input.counts;
  const issuesBySeverity = ["critical", "moderate", "minor", "review"].map((sev) => ({
    sev,
    items: input.issues.filter((i) => i.severity === sev),
  }));

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(input.title)}</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<style>
  :root { color-scheme: light; }
  body { font: 14px/1.55 -apple-system, "Segoe UI", Inter, system-ui, sans-serif;
         color:#0E1422; background:#fff; margin:0; padding:0; }
  main { max-width: 760px; margin: 0 auto; padding: 48px 40px 64px; }
  h1 { font-size: 26px; font-weight: 600; letter-spacing: -0.02em; margin: 0 0 4px; }
  h2 { font-size: 18px; font-weight: 600; margin: 32px 0 12px; }
  h3 { font-size: 14px; font-weight: 600; margin: 16px 0 6px; }
  .meta { color: #4B5570; font-size: 13px; margin-bottom: 24px; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 16px 0 0; }
  .stat { border: 1px solid #E4E8F0; border-radius: 8px; padding: 12px; }
  .stat .n { font-weight: 600; font-size: 22px; tabular-nums: true; }
  .stat .l { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #4B5570; }
  .crit .n { color: #8A2F40; } .mod .n { color: #8C6217; } .min .n { color: #2A50BF; } .rev .n { color: #5E4FD9; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 13px; }
  th, td { padding: 8px 6px; border-bottom: 1px solid #E4E8F0; text-align: left; vertical-align: top; }
  th { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #4B5570; }
  code { font: 12px/1.4 ui-monospace, "SF Mono", Menlo, monospace; background: #F7F8FB; padding: 1px 4px; border-radius: 3px; }
  .pill { display: inline-block; padding: 1px 8px; border-radius: 999px; font-size: 11px; font-weight: 600; }
  .pill-critical { background: #F8E5E9; color: #8A2F40; }
  .pill-moderate { background: #FBF1DE; color: #8C6217; }
  .pill-minor    { background: #EEF3FF; color: #2A50BF; }
  .pill-review   { background: #EFEDFE; color: #5E4FD9; }
  .disclaimer { margin-top: 48px; padding: 18px; border-top: 1px solid #E4E8F0; color: #4B5570; font-size: 12px; }
  @media print {
    body { background: #fff; }
    main { padding: 24px 32px; }
  }
</style>
</head>
<body>
<main>
  <p style="font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#4B5570;font-weight:600;margin:0 0 4px">
    Accessibility assessment
  </p>
  <h1>${escapeHtml(input.title)}</h1>
  <p class="meta">
    ${escapeHtml(input.workspaceName)} · ${escapeHtml(input.baseUrl)} · ${input.pagesScanned} pages ·
    scanned ${input.scanDate.toLocaleDateString()}
  </p>

  <h2>1. Executive summary</h2>
  <p>
    AccessOps AI scanned <strong>${input.pagesScanned}</strong> page(s) of
    <code>${escapeHtml(input.baseUrl)}</code> against WCAG 2.2 AA-oriented checks via axe-core.
    The scan surfaced ${sevCount.critical + sevCount.moderate + sevCount.minor + sevCount.review}
    automated findings, of which ${sevCount.critical} are critical and ${sevCount.moderate} are
    moderate. ${sevCount.review} finding(s) require human review because automated checks could
    not fully decide.
  </p>
  <div class="stats">
    <div class="stat crit"><div class="n">${sevCount.critical}</div><div class="l">Critical</div></div>
    <div class="stat mod"><div class="n">${sevCount.moderate}</div><div class="l">Moderate</div></div>
    <div class="stat min"><div class="n">${sevCount.minor}</div><div class="l">Minor</div></div>
    <div class="stat rev"><div class="n">${sevCount.review}</div><div class="l">Needs review</div></div>
  </div>

  <h2>2. Scan scope &amp; limitations</h2>
  <ul>
    <li>Pages scanned: ${input.pagesScanned}</li>
    <li>Standard: WCAG 2.2 AA-oriented (axe-core ruleset)</li>
    <li>Automated tools detect ~30–50% of accessibility issues; human review remains required.</li>
    <li>Authenticated pages and visual issues that require manual inspection were not covered.</li>
  </ul>

  <h2>3. Findings by severity</h2>
  ${issuesBySeverity
    .map(
      ({ sev, items }) => `
    <h3>${capitalize(sev)} (${items.length})</h3>
    ${
      items.length === 0
        ? `<p style="color:#6B7590">None.</p>`
        : `<table>
      <thead><tr><th>Rule</th><th>Page</th><th>WCAG</th><th>Description</th></tr></thead>
      <tbody>
        ${items
          .map(
            (i) => `
          <tr>
            <td><span class="pill pill-${sev}">${capitalize(sev)}</span><br/><code>${escapeHtml(i.ruleId)}</code></td>
            <td><code>${escapeHtml(i.pageUrl ?? "")}</code></td>
            <td><code>${escapeHtml(i.wcagTags.join(" ") || "—")}</code></td>
            <td>${escapeHtml(i.help)}<br/><span style="color:#6B7590;font-size:12px">${escapeHtml(i.description)}</span></td>
          </tr>`
          )
          .join("")}
      </tbody>
    </table>`
    }
  `
    )
    .join("")}

  <h2>4. Remediation roadmap</h2>
  <ol>
    <li><strong>Week 1 — Critical blockers.</strong> Address every critical finding before non-critical work.</li>
    <li><strong>Week 2 — Forms &amp; keyboard.</strong> Fix form labels, focus visibility, and keyboard traps.</li>
    <li><strong>Week 3 — Structure.</strong> Headings, landmarks, page titles, language attributes.</li>
    <li><strong>Ongoing.</strong> Manual screen-reader pass per release; quarterly multi-page scans.</li>
  </ol>

  <h2>5. Human review checklist</h2>
  <ul>
    <li>Keyboard-only walkthrough of primary user journeys</li>
    <li>Screen reader pass on home, product detail, checkout</li>
    <li>Mobile gesture and zoom test at 200% and 400%</li>
    <li>Reduced-motion preference verification</li>
    <li>Color/contrast manual sampling on hover, focus, and error states</li>
  </ul>

  <div class="disclaimer">${escapeHtml(DISCLAIMER)}</div>
</main>
</body>
</html>`;
}

export function renderCsv(input: ReportInput): string {
  const header = [
    "issue_id",
    "rule_id",
    "severity",
    "impact",
    "wcag_tags",
    "page_url",
    "description",
    "help",
    "help_url",
  ];
  const rows = input.issues.map((i) => [
    i.id,
    i.ruleId,
    i.severity,
    i.impact,
    i.wcagTags.join(";"),
    i.pageUrl ?? "",
    i.description.replace(/\s+/g, " ").trim(),
    i.help.replace(/\s+/g, " ").trim(),
    i.helpUrl ?? "",
  ]);
  const all = [header, ...rows, ["DISCLAIMER", DISCLAIMER]];
  return all
    .map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","))
    .join("\n");
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
