/**
 * Render a report from DB content.
 *
 * Three flavors:
 *   - HTML: produced inline; can be returned as text/html or used to
 *     drive PDF generation later.
 *   - PDF: generated by sending the HTML to the worker via a `pdfFromHtml`
 *     queue (deferred — for MVP we serve the HTML and let the browser
 *     print to PDF). Documented in README.
 *   - CSV: flat issues table, no headers in the body.
 *
 * The disclaimer is always the last block of the HTML and is also
 * embedded as a trailing CSV row so exports can't be stripped of the
 * non-legal notice.
 */
import { COMPLIANCE_COPY } from "@/lib/microcopy/compliance";

export interface ReportEvidence {
  /** base64 PNG data URI — durable in HTML + PDF, no signed-URL expiry. */
  dataUri: string;
  selector: string | null;
  redactionApplied: boolean;
}

export interface ReportInputIssue {
  id: string;
  ruleId: string;
  severity: string;
  impact: string;
  description: string;
  help: string;
  helpUrl?: string | null;
  wcagTags: string[];
  pageUrl: string | null;
  pageTitle: string | null;
  htmlSnippet?: string | null;
  evidence?: ReportEvidence | null;
  groupId?: string | null;
}

export interface ReportGroup {
  id: string;
  ruleId: string;
  title: string;
  severity: string;
  affectedCount: number;
  primaryWcagTag: string | null;
  recommendedFix: string | null;
  priority: number;
}

export interface ReportInput {
  title: string;
  workspaceName: string;
  scanId: string;
  baseUrl: string;
  pagesScanned: number;
  scanDate: Date;
  issues: ReportInputIssue[];
  counts: { critical: number; moderate: number; minor: number; passed: number; review: number };
  groups?: ReportGroup[];
  /**
   * Agency / white-label branding. When `agencyBranding` is true the
   * footer presents the workspace as the author; otherwise the report
   * carries AccessOps AI attribution.
   */
  agencyBranding?: boolean;
}

const DISCLAIMER = COMPLIANCE_COPY.REPORT_NOT_LEGAL;

export function renderHtml(input: ReportInput): string {
  const sevCount = input.counts;
  const evidenceCount = input.issues.filter((i) => i.evidence).length;
  const issuesBySeverity = ["critical", "moderate", "minor", "review"].map((sev) => ({
    sev,
    items: input.issues.filter((i) => i.severity === sev),
  }));
  const groups = input.groups ?? [];
  const useGroups = groups.length > 0;
  const issuesByGroup = new Map<string, ReportInputIssue[]>();
  for (const issue of input.issues) {
    if (!issue.groupId) continue;
    const bucket = issuesByGroup.get(issue.groupId);
    if (bucket) bucket.push(issue);
    else issuesByGroup.set(issue.groupId, [issue]);
  }
  const topFixes = groups.filter((g) => g.severity !== "review").slice(0, 5);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(input.title)}</title>
<meta name="viewport" content="width=device-width,initial-scale=1" />
<style>
  :root { color-scheme: light; }
  body { font: 14px/1.55 -apple-system, "Segoe UI", Inter, system-ui, sans-serif;
         color:#0E1422; background:#fff; margin:0; padding:0; }
  main { max-width: 760px; margin: 0 auto; padding: 48px 40px 64px; }
  h1 { font-size: 26px; font-weight: 600; letter-spacing: -0.02em; margin: 0 0 4px; }
  h2 { font-size: 18px; font-weight: 600; margin: 32px 0 12px; }
  h3 { font-size: 14px; font-weight: 600; margin: 16px 0 6px; }
  .meta { color: #4B5570; font-size: 13px; margin-bottom: 24px; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 16px 0 0; }
  .stat { border: 1px solid #E4E8F0; border-radius: 8px; padding: 12px; }
  .stat .n { font-weight: 600; font-size: 22px; tabular-nums: true; }
  .stat .l { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #4B5570; }
  .crit .n { color: #8A2F40; } .mod .n { color: #8C6217; } .min .n { color: #2A50BF; } .rev .n { color: #5E4FD9; }
  table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 13px; }
  th, td { padding: 8px 6px; border-bottom: 1px solid #E4E8F0; text-align: left; vertical-align: top; }
  th { font-size: 11px; text-transform: uppercase; letter-spacing: 0.06em; color: #4B5570; }
  code { font: 12px/1.4 ui-monospace, "SF Mono", Menlo, monospace; background: #F7F8FB; padding: 1px 4px; border-radius: 3px; }
  .pill { display: inline-block; padding: 1px 8px; border-radius: 999px; font-size: 11px; font-weight: 600; }
  .pill-critical { background: #F8E5E9; color: #8A2F40; }
  .pill-moderate { background: #FBF1DE; color: #8C6217; }
  .pill-minor    { background: #EEF3FF; color: #2A50BF; }
  .pill-review   { background: #EFEDFE; color: #5E4FD9; }
  .evidence { margin-top: 8px; }
  .evidence img { max-width: 100%; border: 1px solid #E4E8F0; border-radius: 6px; display: block; }
  .evidence-meta { font-size: 11px; color: #4B5570; margin-top: 4px; }
  .redacted { display: inline-block; background: #F8E5E9; color: #8A2F40; border-radius: 4px; padding: 0 6px; font-size: 10px; font-weight: 600; }
  .disclaimer { margin-top: 48px; padding: 18px; border-top: 1px solid #E4E8F0; color: #4B5570; font-size: 12px; }
  @media print {
    body { background: #fff; }
    main { padding: 24px 32px; }
  }
</style>
</head>
<body>
<main>
  <p style="font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#4B5570;font-weight:600;margin:0 0 4px">
    Accessibility assessment
  </p>
  <h1>${escapeHtml(input.title)}</h1>
  <p class="meta">
    ${escapeHtml(input.workspaceName)} · ${escapeHtml(input.baseUrl)} · ${input.pagesScanned} pages ·
    scanned ${input.scanDate.toLocaleDateString()}
  </p>

  <h2>1. Executive summary</h2>
  <p>
    AccessOps AI scanned <strong>${input.pagesScanned}</strong> page(s) of
    <code>${escapeHtml(input.baseUrl)}</code> against WCAG 2.2 AA-oriented checks via axe-core.
    The scan surfaced ${sevCount.critical + sevCount.moderate + sevCount.minor + sevCount.review}
    automated findings, of which ${sevCount.critical} are critical and ${sevCount.moderate} are
    moderate. ${sevCount.review} finding(s) require human review because automated checks could
    not fully decide.
  </p>
  <div class="stats">
    <div class="stat crit"><div class="n">${sevCount.critical}</div><div class="l">Critical</div></div>
    <div class="stat mod"><div class="n">${sevCount.moderate}</div><div class="l">Moderate</div></div>
    <div class="stat min"><div class="n">${sevCount.minor}</div><div class="l">Minor</div></div>
    <div class="stat rev"><div class="n">${sevCount.review}</div><div class="l">Needs review</div></div>
  </div>

  <h2>2. Scan scope &amp; limitations</h2>
  <ul>
    <li>Pages scanned: ${input.pagesScanned}</li>
    <li>Standard: WCAG 2.2 AA-oriented (axe-core ruleset)</li>
    <li>Automated tools detect ~30–50% of accessibility issues; human review remains required.</li>
    <li>Authenticated pages and visual issues that require manual inspection were not covered.</li>
    ${evidenceCount > 0 ? `<li>${evidenceCount} finding(s) include diagnostic visual evidence (screenshots); sensitive regions are redacted where detected.</li>` : ""}
  </ul>

  ${
    useGroups && topFixes.length > 0
      ? `<h2>3. Top priority fixes</h2>
  <p>Findings are grouped by root cause. Fixing these collapses the most instances at once.</p>
  <ol>
    ${topFixes
      .map(
        (g) =>
          `<li><strong>${escapeHtml(g.title)}</strong> — ${g.affectedCount} instance(s) · <code>${escapeHtml(g.ruleId)}</code></li>`
      )
      .join("")}
  </ol>`
      : ""
  }

  <h2>${useGroups ? "4. Findings by root cause" : "3. Findings by severity"}</h2>
  ${
    useGroups
      ? groups
          .map((g) => {
            const items = issuesByGroup.get(g.id) ?? [];
            if (!items.length) return "";
            const sev = g.severity;
            const pages = Array.from(
              new Set(items.map((i) => i.pageUrl).filter(Boolean))
            ) as string[];
            const evidenceItem = items.find((i) => i.evidence);
            return `
    <h3><span class="pill pill-${sev}">${capitalize(sev)}</span> ${escapeHtml(g.title)} <span style="color:#6B7590;font-weight:400">(${g.affectedCount} instance${g.affectedCount === 1 ? "" : "s"})</span></h3>
    <p style="color:#6B7590;font-size:13px;margin:4px 0">
      <code>${escapeHtml(g.ruleId)}</code> · ${escapeHtml(g.primaryWcagTag ?? "—")}${g.recommendedFix ? ` · ${escapeHtml(g.recommendedFix)}` : ""}
    </p>
    ${
      pages.length
        ? `<p style="font-size:12px;color:#4B5570">Affected pages: ${pages
            .slice(0, 8)
            .map((p) => `<code>${escapeHtml(p)}</code>`)
            .join(", ")}${pages.length > 8 ? ` +${pages.length - 8} more` : ""}</p>`
        : ""
    }
    ${evidenceItem ? renderEvidence(evidenceItem) : ""}`;
          })
          .join("")
      : issuesBySeverity
          .map(
            ({ sev, items }) => `
    <h3>${capitalize(sev)} (${items.length})</h3>
    ${
      items.length === 0
        ? `<p style="color:#6B7590">None.</p>`
        : `<table>
      <thead><tr><th>Rule</th><th>Page</th><th>WCAG</th><th>Description</th></tr></thead>
      <tbody>
        ${items
          .map(
            (i) => `
          <tr>
            <td><span class="pill pill-${sev}">${capitalize(sev)}</span><br/><code>${escapeHtml(i.ruleId)}</code></td>
            <td><code>${escapeHtml(i.pageUrl ?? "")}</code></td>
            <td><code>${escapeHtml(i.wcagTags.join(" ") || "—")}</code></td>
            <td>${escapeHtml(i.help)}<br/><span style="color:#6B7590;font-size:12px">${escapeHtml(i.description)}</span>${renderEvidence(i)}</td>
          </tr>`
          )
          .join("")}
      </tbody>
    </table>`
    }
  `
          )
          .join("")
  }

  <h2>4. Remediation roadmap</h2>
  <ol>
    <li><strong>Week 1 — Critical blockers.</strong> Address every critical finding before non-critical work.</li>
    <li><strong>Week 2 — Forms &amp; keyboard.</strong> Fix form labels, focus visibility, and keyboard traps.</li>
    <li><strong>Week 3 — Structure.</strong> Headings, landmarks, page titles, language attributes.</li>
    <li><strong>Ongoing.</strong> Manual screen-reader pass per release; quarterly multi-page scans.</li>
  </ol>

  <h2>5. Human review checklist</h2>
  <ul>
    <li>Keyboard-only walkthrough of primary user journeys</li>
    <li>Screen reader pass on home, product detail, checkout</li>
    <li>Mobile gesture and zoom test at 200% and 400%</li>
    <li>Reduced-motion preference verification</li>
    <li>Color/contrast manual sampling on hover, focus, and error states</li>
  </ul>

  <div class="disclaimer">
    ${escapeHtml(DISCLAIMER)}
    <p style="margin-top:10px;color:#6B7590">${
      input.agencyBranding
        ? `Prepared by ${escapeHtml(input.workspaceName)}.`
        : `Prepared with AccessOps AI by ${escapeHtml(input.workspaceName)}.`
    }</p>
  </div>
</main>
</body>
</html>`;
}

/**
 * Per-instance CSV — one row per affected element. Each row also carries
 * its root-cause group columns (id / title / affected count) so the flat
 * export can be pivoted back into the grouped view in a spreadsheet.
 */
export function renderCsv(input: ReportInput): string {
  const groupById = new Map((input.groups ?? []).map((g) => [g.id, g]));
  const header = [
    "issue_id",
    "rule_id",
    "severity",
    "impact",
    "wcag_tags",
    "page_url",
    "page_title",
    "description",
    "help",
    "help_url",
    "html_snippet",
    "has_screenshot",
    "screenshot_redacted",
    "group_id",
    "group_title",
    "group_affected_count",
  ];
  const rows = input.issues.map((i) => {
    const group = i.groupId ? groupById.get(i.groupId) : undefined;
    return [
      i.id,
      i.ruleId,
      i.severity,
      i.impact,
      i.wcagTags.join(";"),
      i.pageUrl ?? "",
      i.pageTitle ?? "",
      i.description.replace(/\s+/g, " ").trim(),
      i.help.replace(/\s+/g, " ").trim(),
      i.helpUrl ?? "",
      (i.htmlSnippet ?? "").replace(/\s+/g, " ").trim().slice(0, 500),
      i.evidence ? "yes" : "no",
      i.evidence?.redactionApplied ? "yes" : "no",
      i.groupId ?? "",
      group?.title ?? "",
      group ? String(group.affectedCount) : "",
    ];
  });
  const all = [header, ...rows, ["DISCLAIMER", DISCLAIMER]];
  return all
    .map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","))
    .join("\n");
}

/**
 * Machine-readable JSON export: normalized + grouped issues with
 * screenshot metadata. Screenshot binaries are intentionally excluded
 * (only metadata is emitted) to keep the payload lean; the HTML/PDF
 * exports carry the embedded images.
 */
export function renderJson(input: ReportInput): string {
  const instanceIdsByGroup = new Map<string, string[]>();
  for (const i of input.issues) {
    if (!i.groupId) continue;
    const arr = instanceIdsByGroup.get(i.groupId);
    if (arr) arr.push(i.id);
    else instanceIdsByGroup.set(i.groupId, [i.id]);
  }

  const payload = {
    schemaVersion: "accessops-report-v1",
    report: {
      title: input.title,
      workspaceName: input.workspaceName,
      generatedAt: new Date().toISOString(),
    },
    scan: {
      id: input.scanId,
      baseUrl: input.baseUrl,
      pagesScanned: input.pagesScanned,
      scanDate: input.scanDate.toISOString(),
    },
    summary: {
      counts: input.counts,
      total:
        input.counts.critical +
        input.counts.moderate +
        input.counts.minor +
        input.counts.review,
    },
    groups: (input.groups ?? []).map((g) => ({
      id: g.id,
      ruleId: g.ruleId,
      title: g.title,
      severity: g.severity,
      affectedCount: g.affectedCount,
      primaryWcagTag: g.primaryWcagTag,
      recommendedFix: g.recommendedFix,
      priority: g.priority,
      instanceIds: instanceIdsByGroup.get(g.id) ?? [],
    })),
    issues: input.issues.map((i) => ({
      id: i.id,
      groupId: i.groupId ?? null,
      ruleId: i.ruleId,
      severity: i.severity,
      impact: i.impact,
      wcagTags: i.wcagTags,
      pageUrl: i.pageUrl,
      pageTitle: i.pageTitle,
      description: i.description,
      help: i.help,
      helpUrl: i.helpUrl ?? null,
      htmlSnippet: i.htmlSnippet ?? null,
      screenshot: i.evidence
        ? {
            captured: true,
            selector: i.evidence.selector,
            redactionApplied: i.evidence.redactionApplied,
          }
        : { captured: false },
    })),
    disclaimer: DISCLAIMER,
  };
  return JSON.stringify(payload, null, 2);
}

function renderEvidence(i: ReportInputIssue): string {
  if (!i.evidence) return "";
  const selector = i.evidence.selector
    ? `<span class="evidence-meta">Selector: <code>${escapeHtml(i.evidence.selector)}</code></span>`
    : "";
  const redacted = i.evidence.redactionApplied
    ? `<span class="redacted">Sensitive regions redacted</span>`
    : "";
  return `<div class="evidence">
    <img src="${i.evidence.dataUri}" alt="Visual evidence for ${escapeHtml(i.ruleId)}" />
    <div class="evidence-meta">${selector} ${redacted}</div>
  </div>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
