import type { ReportInput } from "@/lib/reports/render";

/** Deterministic, fictional data used only for the public sample report. */
export const NORTHWIND_SAMPLE_REPORT: ReportInput = {
  title: "Northwind Commerce — Synthetic Accessibility Assessment",
  workspaceName: "Northwind Commerce (fictional)",
  scanId: "synthetic-pilot-2026-08",
  baseUrl: "https://northwind.example",
  pagesScanned: 12,
  pagesFailedToScan: 0,
  scanDate: new Date("2026-08-20T09:00:00.000Z"),
  counts: { critical: 2, moderate: 3, minor: 1, passed: 148, review: 2 },
  issues: [
    {
      id: "sample-1",
      ruleId: "button-name",
      severity: "critical",
      impact: "critical",
      description: "A checkout icon button has no accessible name.",
      help: "Buttons must have discernible text",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.10/button-name",
      wcagTags: ["wcag2a", "wcag412"],
      pageUrl: "https://northwind.example/checkout",
      pageTitle: "Checkout",
      htmlSnippet: "<button class=\"checkout-next\"><svg aria-hidden=\"true\">…</svg></button>",
      groupId: "group-controls",
    },
    {
      id: "sample-2",
      ruleId: "label",
      severity: "critical",
      impact: "critical",
      description: "The delivery postcode input is missing a programmatic label.",
      help: "Form elements must have labels",
      helpUrl: "https://dequeuniversity.com/rules/axe/4.10/label",
      wcagTags: ["wcag2a", "wcag412"],
      pageUrl: "https://northwind.example/checkout/delivery",
      pageTitle: "Delivery details",
      htmlSnippet: "<input name=\"postcode\" placeholder=\"Postcode\">",
      groupId: "group-forms",
    },
    {
      id: "sample-3",
      ruleId: "color-contrast",
      severity: "moderate",
      impact: "serious",
      description: "Muted product metadata does not meet the target contrast ratio.",
      help: "Elements must meet minimum color contrast ratio thresholds",
      wcagTags: ["wcag2aa", "wcag143"],
      pageUrl: "https://northwind.example/products/harbor-lamp",
      pageTitle: "Harbor lamp",
      htmlSnippet: "<span class=\"product-meta text-slate-400\">In stock</span>",
      groupId: "group-contrast",
    },
    {
      id: "sample-4",
      ruleId: "heading-order",
      severity: "moderate",
      impact: "moderate",
      description: "The account page skips from an h1 to an h3.",
      help: "Heading levels should only increase by one",
      wcagTags: ["best-practice"],
      pageUrl: "https://northwind.example/account/orders",
      pageTitle: "Orders",
      htmlSnippet: "<h3>Recent orders</h3>",
      groupId: "group-structure",
    },
    {
      id: "sample-5",
      ruleId: "link-name",
      severity: "moderate",
      impact: "serious",
      description: "Two wishlist links expose the same generic accessible name.",
      help: "Links must have discernible text",
      wcagTags: ["wcag2a", "wcag412"],
      pageUrl: "https://northwind.example/wishlist",
      pageTitle: "Wishlist",
      htmlSnippet: "<a href=\"/products/harbor-lamp\">View</a>",
      groupId: "group-controls",
    },
    {
      id: "sample-6",
      ruleId: "landmark-one-main",
      severity: "minor",
      impact: "moderate",
      description: "The returns page has no main landmark.",
      help: "Document should have one main landmark",
      wcagTags: ["best-practice"],
      pageUrl: "https://northwind.example/help/returns",
      pageTitle: "Returns",
      htmlSnippet: "<div id=\"content\">…</div>",
      groupId: "group-structure",
    },
    {
      id: "sample-7",
      ruleId: "manual-keyboard-flow",
      severity: "review",
      impact: "moderate",
      description: "Keyboard completion of the checkout flow requires human verification.",
      help: "Review keyboard order and visible focus across the checkout journey",
      wcagTags: ["wcag211", "manual-review"],
      pageUrl: "https://northwind.example/checkout",
      pageTitle: "Checkout",
      groupId: "group-review",
    },
    {
      id: "sample-8",
      ruleId: "manual-screen-reader-status",
      severity: "review",
      impact: "moderate",
      description: "The cart update announcement requires assistive-technology verification.",
      help: "Confirm cart status changes are announced without moving focus",
      wcagTags: ["wcag413", "manual-review"],
      pageUrl: "https://northwind.example/cart",
      pageTitle: "Cart",
      groupId: "group-review",
    },
  ],
  groups: [
    { id: "group-controls", ruleId: "interactive-names", title: "Give interactive controls specific accessible names", severity: "critical", affectedCount: 3, primaryWcagTag: "wcag412", recommendedFix: "Add visible or programmatic names that describe each control's action and destination.", priority: 1 },
    { id: "group-forms", ruleId: "form-labels", title: "Associate every checkout input with a persistent label", severity: "critical", affectedCount: 1, primaryWcagTag: "wcag412", recommendedFix: "Use a label element or an equivalent programmatic association; do not rely on placeholder text.", priority: 2 },
    { id: "group-contrast", ruleId: "design-tokens", title: "Raise contrast in the muted text token", severity: "moderate", affectedCount: 4, primaryWcagTag: "wcag143", recommendedFix: "Update the shared muted-text token and verify it in every supported theme.", priority: 3 },
    { id: "group-structure", ruleId: "document-structure", title: "Repair page landmarks and heading hierarchy", severity: "moderate", affectedCount: 2, primaryWcagTag: null, recommendedFix: "Use one main landmark and a sequential heading outline on each template.", priority: 4 },
    { id: "group-review", ruleId: "manual-review", title: "Verify the critical journey with keyboard and a screen reader", severity: "review", affectedCount: 2, primaryWcagTag: "manual-review", recommendedFix: "Complete the guided review with at least one keyboard-only and one screen-reader pass.", priority: 5 },
  ],
  reportType: "full",
};
