/**
 * Single source of truth for compliance / disclaimer microcopy.
 * Every AI surface, every report, every scan result imports from here.
 */
export const COMPLIANCE_COPY = {
  POSITIONING: "Accessibility operations, not one-click compliance.",

  NO_GUARANTEE_SHORT:
    "AccessOps AI helps identify and manage accessibility issues. It does not guarantee legal compliance.",

  NO_GUARANTEE_FULL:
    "AccessOps AI helps identify and manage accessibility issues. Automated tools cannot detect every accessibility issue, and this product does not guarantee ADA, EAA, WCAG, Section 508, or EN 301 549 compliance. Consult a qualified accessibility or legal professional for formal compliance claims.",

  AUTOMATED_LIMITATIONS:
    "Automated accessibility scanning has limitations. Human review may be required to verify findings and identify issues that automated checks cannot detect.",

  AI_REVIEW_REQUIRED: "AI-generated suggestion. Review before implementation.",

  AI_DISCLOSURE:
    "Some explanations, summaries, and remediation suggestions in this product are generated by AI models. AI output can be incomplete or incorrect. Always review AI suggestions before applying them to your code or sharing with clients.",

  HUMAN_REVIEW:
    "Human review may be required for issues that automated checks cannot fully verify.",

  REPORT_NOT_LEGAL:
    "This report is an accessibility assessment aid, not a legal certification. It reflects findings at the time of the scan and does not certify compliance with any law, regulation, or standard.",

  SCAN_PERMISSION:
    "I confirm I own this website or have permission to scan it and capture diagnostic accessibility evidence.",

  SCAN_PRIVACY:
    "Do not scan private dashboards or pages containing sensitive personal data. Use authenticated scanning carefully and only on properties you own or operate.",

  ONBOARDING_BOUNDARY:
    "AccessOps AI helps you identify and manage accessibility issues. It does not provide legal certification or guarantee compliance with any specific law, regulation, or standard.",

  ONBOARDING_ACK:
    "I understand that automated accessibility scanning has limitations and that human review may be required.",

  OVERLAY_STANCE:
    "AccessOps AI is not an accessibility overlay. We do not recommend overlay-only fixes as a substitute for real remediation.",

  DELETE_SCAN_WARNING:
    "Deleting scan data is permanent. Reports built from this scan will lose their underlying findings.",

  SCREENSHOT_NOTICE:
    "Screenshots are captured only for diagnostic accessibility evidence. Avoid scanning pages containing personal, confidential, financial, medical, or highly sensitive information unless you have authorization.",

  VISUAL_EVIDENCE_WARNING:
    "Visual evidence is diagnostic only and may contain third-party copyrighted or personal data. Do not redistribute publicly.",
} as const;

export const FORBIDDEN_AI_CLAIMS = [
  "fully compliant",
  "100% compliant",
  "certified",
  "legally compliant",
  "guaranteed compliance",
] as const;
